spring:
  application:
    name: task-management-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
